import { render, screen } from '@testing-library/react';
import React from 'react';
import { beforeEach, describe, expect, it } from 'vitest';

import { initialRuntimeState, useRuntimeStore } from '@/store/runtime';

import { styles as decorativeStyles } from './DecorativeLayer/style';
import { styles as headerStyles } from './Header/style';
import RuntimeWorkspace from './index';
import { styles as pluginStyles } from './PluginPanel/style';
import { styles as sidebarStyles } from './Sidebar/style';
import { styles as workspaceStyles } from './style';

describe('RuntimeWorkspace Responsive & Reduced-Motion Contracts', () => {
  beforeEach(() => {
    useRuntimeStore.setState({
      ...initialRuntimeState,
    });
  });

  it('renders workspace with responsive mainContent container and decorative overlay', () => {
    render(<RuntimeWorkspace />);

    const workspace = screen.getByTestId('runtime-workspace');
    expect(workspace).toBeInTheDocument();
    expect(workspace.className).toContain(workspaceStyles.workspace);

    const mainContent = screen.getByTestId('workspace-main-content');
    expect(mainContent).toBeInTheDocument();
    expect(mainContent.className).toContain(workspaceStyles.mainContent);

    const decorative = screen.getByTestId('decorative-layer');
    expect(decorative).toHaveAttribute('aria-hidden', 'true');
    expect(decorative.className).toContain(decorativeStyles.container);
  });

  it('DecorativeLayer style contract includes prefers-reduced-motion declarations', () => {
    expect(decorativeStyles.accentGlow).toBeDefined();
    expect(decorativeStyles.container).toBeDefined();
    expect(decorativeStyles.gridOverlay).toBeDefined();
    // Verify class names are non-empty strings generated by createStaticStyles
    expect(typeof decorativeStyles.accentGlow).toBe('string');
    expect(typeof decorativeStyles.gridOverlay).toBe('string');
  });

  it('Sidebar style contract includes mobile stacking and reduced motion rules', () => {
    expect(sidebarStyles.sidebar).toBeDefined();
    expect(sidebarStyles.item).toBeDefined();
    expect(sidebarStyles.list).toBeDefined();
    expect(typeof sidebarStyles.sidebar).toBe('string');
  });

  it('PluginPanel style contract includes tablet and mobile responsive rules', () => {
    expect(pluginStyles.panel).toBeDefined();
    expect(pluginStyles.list).toBeDefined();
    expect(typeof pluginStyles.panel).toBe('string');
  });

  it('Header style contract supports wrapping and responsive padding', () => {
    expect(headerStyles.header).toBeDefined();
    expect(headerStyles.meta).toBeDefined();
    expect(typeof headerStyles.header).toBe('string');
  });

  it('allows disabling plugins and composer via props on compact layouts', () => {
    render(<RuntimeWorkspace showComposer={false} showPlugins={false} />);

    expect(screen.queryByTestId('run-composer')).not.toBeInTheDocument();
    expect(screen.queryByTestId('workspace-plugin-panel')).not.toBeInTheDocument();
    expect(screen.getByTestId('workspace-main-content')).toBeInTheDocument();
  });
});
