import type { ModelProviderCard } from '@/types/llm';

const Nexus: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 1_050_000,
      displayName: 'GPT-5.5',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.5',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 1_050_000,
      displayName: 'GPT-5.4',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.4',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 400_000,
      displayName: 'GPT-5.4 mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.4-mini',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 400_000,
      displayName: 'GPT-5.3 Codex',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.3-codex',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 400_000,
      displayName: 'GPT-5.2',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.2',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 400_000,
      displayName: 'GPT-5.4 OpenAI Compact',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.4-openai-compact',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
    {
      contextWindowTokens: 400_000,
      displayName: 'GPT-5.5 OpenAI Compact',
      enabled: true,
      functionCall: true,
      id: 'gpt-5.5-openai-compact',
      maxOutput: 128_000,
      reasoning: true,
      search: true,
      type: 'chat',
      vision: true,
    },
  ],
  checkModel: 'gpt-5.4-mini',
  description: 'Qingzhou OpenAI-compatible gateway for chat and native image generation.',
  enabled: true,
  id: 'nexus',
  name: 'Qingzhou',
  settings: {
    disableBrowserRequest: true,
    proxyUrl: {
      desc: '填写 OpenAI 兼容的图像生成服务地址。留空时使用清舟默认服务。',
      placeholder: 'https://app.soruxgpt.com/api/codex/v1',
      title: 'Base URL',
    },
    showChecker: false,
  },
  url: 'https://app.soruxgpt.com',
};

export default Nexus;
